language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pawanpoudel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pawanpoudel/react-test npm run test

after_success:
  - docker build -t pawanpoudel/multi-client ./client
  - docker build -t pawanpoudel/multi-nginx ./nginx
  - docker build -t pawanpoudel/multi-server ./server
  - docker build -t pawanpoudel/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pawanpoudel/multi-client
  - docker push pawanpoudel/multi-nginx
  - docker push pawanpoudel/multi-server
  - docker push pawanpoudel/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-381491950879"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
